[settings]
experimental = true
python.uv_venv_auto = true

[env]
GITHUB_REPO_OWNER = "hotdog-werx"
GITHUB_REPO_NAME = "{{ config_root | basename }}"
GITHUB_REPO = "{{ env.GITHUB_REPO_OWNER }}/{{ env.GITHUB_REPO_NAME }}"
GIT_CLIFF_CONFIG = "./.pkglink/.codeguide/configs/cliff.toml"

[tasks]
pkglink.run = "mise exec -- pkglink sync"
setup-hook.run = "mise exec -- poe setup-hook"

[hooks]
postinstall = ["mise run pkglink", "mise run setup-hook"]

[tools]
uv = "0.9.27"
dprint = "0.51.1"
starship = "1.24.2"
git-cliff = "2.12.0"
actionlint = "1.7.10"
shellcheck = "0.11.0"

"pipx:poethepoet" = "0.40.0"
"pipx:pkglink" = "1.1.0"
"pipx:tbelt" = "0.0.3"
"pipx:ruff" = "0.14.14"
"pipx:hotdog-werx/releez" = "0.2.0"
"pipx:zensical" = "0.0.19"
"pipx:ty" = "0.0.14"
