name: CI checks

on:
  pull_request:
  push:
    branches:
      - master

permissions:
  contents: read

jobs:
  checks:
    name: Run checks (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install mise tools
        uses: jdx/mise-action@v3

      - name: Sync with pkglink
        run: pkglink sync

      - name: Install python dependencies
        run: uv sync --all-groups

      - name: Run dprint check
        run: poe check-dprint

      - name: Run Python checks
        run: poe check-python

      - name: Run complexity check
        run: poe check-complexity

      - name: Run type check
        run: poe check-basedpyright

      - name: Run coverage check
        run: poe check-coverage

      - name: Generate coverage XML report
        run: uv run coverage xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
